apiVersion: v1
kind: Namespace
metadata:
  name: cloudapp
  labels:
    name: cloudapp
    environment: dev
    project: cloud-native-app
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cloudapp-quota
  namespace: cloudapp
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cloudapp-limits
  namespace: cloudapp
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
